// lib/mock-data/jobs.ts
import type { JobSummary, JobDetail } from '../types';

export const mockJobs: JobSummary[] = [
  {
    id: 'job-001',
    source: 'CLIENT_POSTED',
    status: 'PUBLISHED',
    cargoType: 'GENERAL',
    weightKg: 5000,
    originCity: 'Casablanca',
    destCity: 'Marrakech',
    pickupDateFrom: '2026-07-10',
    deliveryDate: '2026-07-12',
    bidCount: 3,
    createdAt: '2026-06-28T09:00:00Z',
  },
  {
    id: 'job-002',
    source: 'CLIENT_POSTED',
    status: 'ACCEPTED',
    cargoType: 'REFRIGERATED',
    weightKg: 2000,
    originCity: 'Agadir',
    destCity: 'Casablanca',
    pickupDateFrom: '2026-07-08',
    deliveryDate: '2026-07-10',
    bidCount: 1,
    agreedPriceMAD: 4500,
    createdAt: '2026-06-25T11:30:00Z',
  },
  {
    id: 'job-003',
    source: 'CLIENT_POSTED',
    status: 'IN_TRANSIT',
    cargoType: 'FRAGILE',
    weightKg: 800,
    originCity: 'Rabat',
    destCity: 'Fès',
    pickupDateFrom: '2026-07-01',
    deliveryDate: '2026-07-03',
    bidCount: 1,
    agreedPriceMAD: 2200,
    createdAt: '2026-06-20T08:15:00Z',
  },
  {
    id: 'job-004',
    source: 'RETURN_TRIP',
    status: 'ACCEPTED',
    cargoType: 'GENERAL',
    weightKg: 10000,
    originCity: 'Tanger',
    destCity: 'Casablanca',
    pickupDateFrom: '2026-07-15',
    deliveryDate: '2026-07-16',
    bidCount: 0,
    agreedPriceMAD: 6000,
    createdAt: '2026-06-29T14:00:00Z',
  },
  {
    id: 'job-005',
    source: 'CLIENT_POSTED',
    status: 'COMPLETED',
    cargoType: 'OVERSIZED',
    weightKg: 18000,
    originCity: 'Casablanca',
    destCity: 'Agadir',
    pickupDateFrom: '2026-06-10',
    deliveryDate: '2026-06-12',
    bidCount: 1,
    agreedPriceMAD: 11000,
    createdAt: '2026-06-05T07:00:00Z',
  },
  {
    id: 'job-006',
    source: 'CLIENT_POSTED',
    status: 'CANCELLED',
    cargoType: 'HAZMAT',
    weightKg: 3000,
    originCity: 'Oujda',
    destCity: 'Rabat',
    pickupDateFrom: '2026-06-20',
    deliveryDate: '2026-06-22',
    bidCount: 0,
    createdAt: '2026-06-15T10:00:00Z',
  },
  // ── Northern corridor jobs (for the carrier map / on-the-way suggestions) ──
  {
    id: 'job-007',
    source: 'CLIENT_POSTED',
    status: 'PUBLISHED',
    cargoType: 'GENERAL',
    weightKg: 4200,
    originCity: 'Nador',
    destCity: 'Tétouan',
    pickupDateFrom: '2026-07-09',
    deliveryDate: '2026-07-10',
    bidCount: 2,
    createdAt: '2026-06-30T08:00:00Z',
  },
  {
    id: 'job-008',
    source: 'CLIENT_POSTED',
    status: 'PUBLISHED',
    cargoType: 'FRAGILE',
    weightKg: 1500,
    originCity: 'Al Hoceima',
    destCity: 'Tanger',
    pickupDateFrom: '2026-07-09',
    deliveryDate: '2026-07-10',
    bidCount: 1,
    createdAt: '2026-06-30T09:30:00Z',
  },
  {
    id: 'job-009',
    source: 'CLIENT_POSTED',
    status: 'PUBLISHED',
    cargoType: 'REFRIGERATED',
    weightKg: 2600,
    originCity: 'Taza',
    destCity: 'Fès',
    pickupDateFrom: '2026-07-11',
    deliveryDate: '2026-07-12',
    bidCount: 0,
    createdAt: '2026-06-30T10:15:00Z',
  },
  {
    id: 'job-010',
    source: 'CLIENT_POSTED',
    status: 'PUBLISHED',
    cargoType: 'OVERSIZED',
    weightKg: 15000,
    originCity: 'Oujda',
    destCity: 'Casablanca',
    pickupDateFrom: '2026-07-12',
    deliveryDate: '2026-07-14',
    bidCount: 1,
    createdAt: '2026-06-30T11:00:00Z',
  },
];

export const mockJobDetails: Record<string, JobDetail> = {
  'job-001': {
    ...mockJobs[0],
    description:   'Marchandises générales en palettes — 50 cartons de produits ménagers. Chargement au dépôt.',
    fragile:       false,
    hazmat:        false,
    originAddress: 'Zone Industrielle Aïn Sebaâ, Casablanca',
    destAddress:   'Dépôt central, Route de Casablanca, Marrakech',
    notes:         'Accès camion disponible entre 7h et 17h.',
    photoUrls:     [],
    bids:          [],
    client:        { clientType: 'BUSINESS', companyName: 'Imex Maroc SARL', fullName: 'Karim Benali', phone: '+212 6 12 34 56 78' },
  },
  'job-002': {
    ...mockJobs[1],
    description:   'Produits frais sous température contrôlée (0–4°C). Fruits et légumes biologiques.',
    fragile:       false,
    hazmat:        false,
    originAddress: 'Marché de gros Inezgane, Agadir',
    destAddress:   'Marché central, Hay Mohammadi, Casablanca',
    photoUrls:     [],
    bids:          [],
    client:        { clientType: 'BUSINESS', companyName: 'BioFruits Sud SARL', fullName: 'Omar El Fassi', phone: '+212 6 78 90 12 34' },
  },
  'job-003': {
    ...mockJobs[2],
    description:   'Équipements électroniques en cartons sécurisés. Manipuler avec précaution.',
    fragile:       true,
    hazmat:        false,
    originAddress: 'Technopole Rabat-Salé, Rue de la Paix, Rabat',
    destAddress:   'Zone Industrielle Sidi Brahim, Fès',
    photoUrls:     [],
    bids:          [],
    client:        { clientType: 'INDIVIDUAL', fullName: 'Salma Bennani', phone: '+212 6 70 88 99 00' },
  },
};
