// lib/mock-data/returns.ts
import type { ReturnTrip } from '../types';

export const mockReturnTrips: ReturnTrip[] = [
  {
    id:             'rt-001',
    carrierId:      'carrier-001',
    carrierName:    'Atlas Transport Casablanca',
    carrierCity:    'Casablanca',
    originCity:     'Marrakech',
    destCity:       'Casablanca',
    availableDate:  '2026-07-11',
    capacityKg:     8000,
    vehicleType:    'Camion 12T',
    listedPriceMAD: 3200,
    notes:          'Retour à vide depuis Marrakech. Disponible toute la journée.',
    status:         'OPEN',
  },
  {
    id:             'rt-002',
    carrierId:      'carrier-002',
    carrierName:    'Marrakech Express Freight',
    carrierCity:    'Marrakech',
    originCity:     'Agadir',
    destCity:       'Rabat',
    availableDate:  '2026-07-14',
    capacityKg:     5000,
    vehicleType:    'Camion 7.5T',
    listedPriceMAD: 4800,
    notes:          'Chargement partiel accepté.',
    status:         'OPEN',
  },
  {
    id:             'rt-003',
    carrierId:      'carrier-004',
    carrierName:    'Souss Logistique SARL',
    carrierCity:    'Agadir',
    originCity:     'Tanger',
    destCity:       'Casablanca',
    availableDate:  '2026-07-09',
    capacityKg:     15000,
    vehicleType:    'Semi-remorque 26T',
    listedPriceMAD: 7500,
    status:         'OPEN',
  },
  {
    id:             'rt-004',
    carrierId:      'carrier-005',
    carrierName:    'Nord Fret Tanger',
    carrierCity:    'Tanger',
    originCity:     'Fès',
    destCity:       'Tanger',
    availableDate:  '2026-07-17',
    capacityKg:     3500,
    vehicleType:    'Camion 7.5T',
    listedPriceMAD: 2600,
    notes:          'Flexibilité sur la date ±1 jour.',
    status:         'OPEN',
  },
];
